name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.ACR_NAMESPACE}}.azurecr.io
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}

    - name: Build producer image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cmd/producer/Dockerfile
        push: true
        tags: ${{secrets.ACR_NAMESPACE}}.azurecr.io/producer:latest